platform :ios, '6.0'

pod 'AFNetworking', '1.3.3'
pod 'SVProgressHUD'
pod 'SocketRocket'
pod 'socket.IO'
pod 'Google-Maps-iOS-SDK'
pod 'URBSegmentedControl'
pod 'SVSegmentedControl'
pod 'ASIHTTPRequest'
